# Generated by Django 4.2.3 on 2023-11-26 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_rename_user_subscription_member_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="end",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 26, 10, 4, 26, 213731)
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="start",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 26, 10, 4, 26, 213731)
            ),
        ),
    ]
