# Generated by Django 4.2.3 on 2023-11-28 12:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gym", "0003_alter_attendance_end_alter_attendance_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 28, 17, 28, 47, 79438)
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 11, 28, 17, 28, 47, 79438)
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
