# Generated by Django 4.2.3 on 2023-12-10 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0004_gymsession_delete_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="days",
        ),
        migrations.AddField(
            model_name="plan",
            name="sessions",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gymsession",
            name="end",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gymsession",
            name="start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], max_length=15
            ),
        ),
    ]
