# Generated by Django 4.2.3 on 2023-12-12 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_remove_plan_days_plan_sessions_alter_gymsession_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymsession",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gym.subscription",
            ),
        ),
    ]
