# Generated by Django 4.2.3 on 2024-01-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0001_initial"),
        ("gym", "0008_gym_plan_gym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="gym",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="controls.gym",
            ),
        ),
        migrations.DeleteModel(
            name="Gym",
        ),
    ]
