# Generated by Django 4.2.3 on 2024-01-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0002_rename_sessions_gymplan_members_limit"),
        ("gym", "0009_alter_plan_gym_delete_gym"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="gym",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="controls.gym",
            ),
        ),
    ]
