# Generated by Django 4.2.3 on 2024-01-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0010_subscription_gym"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="gym",
        ),
    ]
