# Generated by Django 4.2.3 on 2024-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0012_subscription_gym_subscri_member__f91a02_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="days",
            field=models.SmallIntegerField(default=1),
        ),
    ]
