# Generated by Django 4.2.3 on 2024-02-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0013_plan_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
