# Generated by Django 4.2.3 on 2024-03-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0015_gymprogram"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QRCode",
        ),
    ]
