# Generated by Django 4.2.3 on 2024-06-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0009_gym_code"),
        ("gym", "0016_delete_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="controls.gym"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
