# Generated by Django 4.2.3 on 2024-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0017_gymequipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymequipment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gym/equipment"),
        ),
    ]
