version: '3.8'

services:
  web_service:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .docker.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - IS_DOCKER=1

  postgres:
    image: postgres:15-alpine
    env_file: .docker.env
    restart: always
    environment:
      POSTGRES_LOGGING_COLLECTOR: "true"
      POSTGRES_LOGGING_MIN_MESSAGES: "DEBUG1"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2-alpine
    env_file:
      - .docker.env
    volumes:
      - redis_data:/data

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - '8000:80'
      - '443:443'

    depends_on:
      - web_service
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  media_volume:
  static_volume:
  postgres_data:
  redis_data:
