version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_HOST : "db"
      POSTGRES_PORT : "5432"
      POSTGRES_NAME : "gymbro"
      POSTGRES_USER : "askar"
      POSTGRES_PASSWORD : "salom123"
      POSTGRES_HOST_AUTH_METHOD : "trust"
  gym:
    restart: always
    build: ./
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - gym-django:/usr/src/app
      - gym-static:/usr/src/app/project/static
    env_file: .env
    depends_on:
      - db
    command: gunicorn project.wsgi:application -w 2 -b :8000 && python manage.py migrate

volumes:
  gym-django:
  gym-static:
  postgres-data:
