# Generated by Django 4.2.3 on 2023-11-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="breasts",
            new_name="chest",
        ),
    ]
