# Generated by Django 4.2.3 on 2024-01-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0002_rename_sessions_gymplan_members_limit"),
        ("users", "0007_gymrole_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gym",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="controls.gym",
            ),
        ),
    ]
