# Generated by Django 4.2.3 on 2024-01-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_gym"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="users_user_phone_n_7fe504_idx"
            ),
        ),
    ]
