# Generated by Django 4.2.3 on 2024-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0006_gym_telegram_bot_token_alter_gymnotification_send_at"),
        ("users", "0009_user_users_user_phone_n_7fe504_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gym",
        ),
        migrations.AddField(
            model_name="user",
            name="gyms",
            field=models.ManyToManyField(related_name="users", to="controls.gym"),
        ),
    ]
