# Generated by Django 4.2.3 on 2024-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_user_gym_user_gyms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.gymrole"
            ),
        ),
    ]
