# Generated by Django 4.2.3 on 2024-03-24 07:13

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="access",
            name="image",
            field=models.ImageField(upload_to=apps.users.models.Access.upload_path),
        ),
    ]
