# Generated by Django 4.2.3 on 2024-06-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_lead"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("-id", "-updated_at")},
        ),
    ]
