# Generated by Django 4.2.3 on 2024-02-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("controls", "0007_gymplan_telegram_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("subdomain", models.CharField(max_length=20, unique=True)),
                (
                    "gym",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="controls.gym"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
