# Generated by Django 4.2.3 on 2024-01-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gymplan",
            old_name="sessions",
            new_name="members_limit",
        ),
    ]
