# Generated by Django 4.2.3 on 2024-02-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0004_gymnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymnotification",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gymnotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "info"),
                    ("warning", "warning"),
                    ("success", "success"),
                    ("danger", "danger"),
                ],
                default="info",
                max_length=7,
            ),
        ),
    ]
