# Generated by Django 4.2.3 on 2024-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0005_gymnotification_body_gymnotification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="telegram_bot_token",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="gymnotification",
            name="send_at",
            field=models.DateTimeField(null=True),
        ),
    ]
