# Generated by Django 4.2.3 on 2024-02-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0006_gym_telegram_bot_token_alter_gymnotification_send_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymplan",
            name="telegram_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
