# Generated by Django 4.2.3 on 2024-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controls", "0008_remove_gymplan_telegram_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
