# Generated by Django 4.2.3 on 2024-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("sms", "sms"), ("telegram", "telegram")], default="telegram"
            ),
        ),
    ]
