# Generated by Django 4.2.3 on 2024-03-15 18:19

import apps.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_sent_alter_notification_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.notifications.models.content_file_name,
            ),
        ),
    ]
